config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"

  resources :genres, only: [:index, :show, :new, :create, :edit, :update]
  resources :directors, only: [:index, :show, :new, :create, :edit, :update]
  resources :movies, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all()
  end

  def show
    @director = Director.find(params[:id])
    @movies = @director.movies
  end

  def director_params
    params.require(:director).permit(
      :name,
      :nationality,
      :birth_date,
      :genre_id
    )
  end

  def create
    director = Director.new(director_params)
    return render:new unless director.save
    redirect_to directors_path
  end

  def new
    @director = Director.new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])
    return render:new unless @director.update(director_params)
    redirect_to director_path(@director.id)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all()
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  def create
    genre = Genre.new(genre_params)
    return render:new unless genre.save
    redirect_to genres_path
  end

  def new
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    return render:new unless @genre.update(genre_params)
    redirect_to genre_path(@genre.id)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all()
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(
      :title,
      :release_date,
      :summary,
      :country,
      :duration,
      :director_id,
      :genre_id,
      :image_url,
      :is_released
      )
  end

  def create
    movie = Movie.new(movie_params)
    return render:new unless movie.save
    redirect_to movies_path
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
    render 'new'
  end

  def update
    @movie = Movie.find(params[:id])
    return render:new unless @movie.update(movie_params)
    redirect_to movie_path(@movie.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<%= form_with model: director, class: "container-sm w-25" do |f| %>
  <div class="mt-3">
    <%= f.label "Director's Name", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>     
  </div>

  <div class="mt-3">
    <%= f.label "Nationality", class: "form-label" %>
    <%= f.text_field :nationality, class: "form-control" %>     
  </div>

  <div class="mt-3">
    <%= f.label "Birthday", class: "form-label" %>
    <%= f.date_field :birth_date, class: "form-control datepicker" %>     
  </div>

  <div class="mt-3">
    <%= f.label "Favourite Genre", class: "form-label" %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name,  { prompt: "Select a genre" }, { class: "form-select" }%>     
  </div>

  <%= f.submit "save", class: "btn btn-dark mt-2"%>  
<% end %>

app/views/directors/edit.html.erb
<%= render partial: "form", locals: {director: @director} %>

app/views/directors/index.html.erb
<div class="container w-50 ">
  <div class="shadow container-sm mt-4 p-4 bg-dark-subtle rounded">
    <% @directors.each do |director| %>
      <div class="row py-2 my-2 rounded border border-dark">
        <%= link_to director.name, director_path(director.id), class: "btn" %>
      </div>
    <% end %>
  </div>

  <div class="mt-2 mb-4">
    <%= link_to new_director_path, class: "btn btn-dark" do %>
      Add new Director
    <% end %>
  </div>
</div>

app/views/directors/new.html.erb
<%= render partial: "form", locals: {director: @director} %>

app/views/directors/show.html.erb
<div class="container w-50 ">
  <div class="shadow container-sm mt-4 p-4 bg-dark-subtle rounded">
    <p>Name: <span class="fw-bold"><%= @director.name%></span></p>
    <p>Nationality: <span class="fw-bold"><%= @director.nationality%></span></p>
    <p>Favourite Genre: <span class="fw-bold"><%= @director.genre.name%></span></p>
    <p>Birthday: <span class="fw-bold"><%= @director.birth_date%></span></p>
    <div class="container-sm mt-2">
      <%= link_to "Edit", edit_director_path, class: "btn btn-dark"%>
    </div>
  </div>
</div>

<div class="container w-50 mt-3">
  <div class="shadow container-sm mt-4 p-4 bg-dark-subtle rounded text-center">
    <h3 class="pb-3">Movies from <%= @director.name %></h3>
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-sm-3 w-25 position-relative pt-2">
          <p><%= movie.is_released ? "Available" : "Coming Soon..." %></p>
          <a href="<%= movie_path(movie) %>">
          <div class="shadow card">          
            <img src="<%= movie.image_url%>" alt="image" class="card-img-top">
            <div class="position-absolute top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-start bg-dark bg-opacity-50  bg-gradient">
              <div class="text-white fw-semibold pt-4"><%= "#{movie.release_date.strftime("%Y")}" %></div>
            </div>
            <div class="position-absolute top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-start">
              <div class="text-light fw-semibold pt-1"><%= movie.title %></div>
            </div>
          </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>




   

app/views/genres/_form.html.erb
<%= form_with model: genre, class: "container-sm w-25" do |f| %>
  <div class="mt-3">
    <%= f.label "Genre Name", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>  
  </div>
  <%= f.submit "save", class: "btn btn-dark mt-2"%>  
<% end %>

app/views/genres/edit.html.erb
<%= render partial: "form", locals: {genre: @genre} %>

app/views/genres/index.html.erb
<div class="container w-50 ">
  <div class="shadow container-sm mt-4 p-4 bg-dark-subtle rounded">
    <% @genres.each do |genre| %>
      <div class="row py-2 my-2 rounded border border-dark">
        <%= link_to genre.name, genre_path(genre.id), class: "btn" %>
      </div>
    <% end %>
  </div>

  <div class="mt-2 mb-4">
    <%= link_to new_genre_path, class: "btn btn-dark" do %>
      Add new Genre
    <% end %>
  </div>
</div>

app/views/genres/new.html.erb
<%= render partial: "form", locals: {genre: @genre} %>

app/views/genres/show.html.erb
<div class="container w-75 ">
  <div class="shadow container-sm mt-4 p-4 bg-dark-subtle rounded text-center">
    <h3><%= "#{@genre.name} movies" %></h3>
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-sm-4 w-25 position-relative pt-2">
          <a href="<%= movie_path(movie) %>">
          <div class="shadow card">          
            <img src="<%= movie.image_url%>" alt="image" class="card-img-top">
            <div class="position-absolute top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-start bg-dark bg-opacity-50  bg-gradient">
              <div class="text-white fw-semibold fs-5 pt-5"><%= "#{movie.genre.name} • #{movie.release_date.strftime("%Y")}" %></div>
            </div>
            <div class="position-absolute top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-start">
              <div class="text-light fw-semibold fs-2 pt-1"><%= movie.title %></div>
            </div>
          </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-2 mb-4">
    <%= link_to "Edit Genre", edit_genre_path, class: "btn btn-dark"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthyTomatoes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  
  <header>
    <nav class="navbar navbar-expand-lg bg-dark-subtle py-2 px-5"> 
      <a class="navbar-brand position-absolute" href="/">Healthy Tomatoes</a>
      <div class="mx-auto"> 
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav gap-2">
            <li class="nav-item">
              <a class="btn btn-sm btn-outline-secondary" href=<%= movies_path %>>Movies</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-sm btn-outline-secondary" href=<%= directors_path %>>Directors</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-sm btn-outline-secondary" href=<%= genres_path %>>Genres</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body class="bg-secondary">
    <div >
      <%= yield %>
      <script async src="https://cdn.jsdelivr.net/npm/es-module-shims@1/dist/es-module-shims.min.js" crossorigin="anonymous"></script>
      <script type="importmap">
      {
        "imports": {
          "@popperjs/core": "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js",
          "bootstrap": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.esm.min.js"
        }
      }
      </script>
      <script type="module">
        import * as bootstrap from 'bootstrap'

        new bootstrap.Popover(document.getElementById('popoverButton'))
      </script>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie, class: "container-sm w-50" do |f| %>
  <div class="mt-3">
    <%= f.label "Title", class: "form-label" %>
    <%= f.text_field :title, class: "form-control" %>     
  </div>

  <div class="mt-3">
    <%= f.label "Release Date", class: "form-label" %>
    <%= f.date_field :release_date, class: "form-control" %>     
  </div>

  <div class="mt-3">
    <%= f.label "Summary", class: "form-label" %>
    <%= f.text_area :summary, class: "form-control datepicker", rows:"4" %>     
  </div>

  <div class="mt-3 row">
    <div class="col">
      <%= f.label "Poster Image URL", class: "form-label" %>
      <%= f.text_field :image_url, class: "form-control"%> 
    </div>
    <div class="col d-flex justify-content-center align-items-center pt-4 ">
      <div class="form-check">
        <%= f.label "Is Released?", class: "form-check-label" %>
        <%= f.check_box :is_released, class: "form-check-input"%> 
      </div>
    </div>
  </div>

  <div class="mt-3 row">
    <div class="col">
      <%= f.label "Country", class: "form-label" %>
      <%= f.text_field :country, class: "form-control datepicker" %>
    </div>
    <div class="col">
      <%= f.label "Duration", class: "form-label" %>
      <%= f.number_field :duration, class: "form-control datepicker" %>
    </div>    
  </div>

  <div class="mt-3 row">
    <div class="col">
      <%= f.label "Director", class: "form-label" %>
      <%= f.collection_select :director_id, Director.all, :id, :name,  { prompt: "Select a Director" }, { class: "form-select" }%>
    </div>
    <div class="col">
       <%= f.label "Genre", class: "form-label" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :name,  { prompt: "Select a genre" }, { class: "form-select" }%> 
    </div>
  </div>

  <%= f.submit "save", class: "btn btn-dark mt-2"%>  
<% end %>

app/views/movies/edit.hmtl.erb
<!-- app/views/movies/edit.html.erb -->
<%= puts "Rendering edit template" %>

<%= render partial: "form", locals: {movie: @movie} %>

app/views/movies/index.html.erb
<div class="container">
  <div class="shadow container-sm mt-4 p-4 bg-dark-subtle rounded">
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-sm-4 w-25 position-relative pt-2 text-center">
          <p><%= movie.is_released ? "Available" : "Coming Soon..." %></p>
          <a href="<%= movie_path(movie) %>">
            <div class="shadow card">          
              <img src="<%= movie.image_url%>" alt="image" class="card-img-top">
              <div class="position-absolute top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-start bg-dark bg-opacity-50  bg-gradient">
                <div class="text-white fw-semibold fs-5 pt-5"><%= "#{movie.genre.name} • #{movie.release_date.strftime("%Y")}" %></div>
              </div>
              <div class="position-absolute top-0 start-0 w-100 h-100 d-flex justify-content-center align-items-start">
                <div class="text-light fw-semibold fs-2 pt-1"><%= movie.title %></div>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-2 mb-4">
    <%= link_to new_movie_path, class: "btn btn-ark" do %>
      Add new Movie
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<%= render partial: "form", locals: {movie: @movie} %>

app/views/movies/show.html.erb
<div class="container w-50 ">
  <div class="shadow container-sm mt-4 p-4 bg-dark-subtle rounded">
    <p>Title: <span class="fw-bold"><%= @movie.title%></span></p>
    <p>Directed by: <span class="fw-bold"><%= @movie.director.name%></span></p>
    <p>Genre: <span class="fw-bold"><%= @movie.genre.name%></span></p>
    <p>Released: <span class="fw-bold"><%= @movie.release_date%></span></p>
    <p>Country of origin: <span class="fw-bold"><%= @movie.country%></span></p>
    <p>Duration: <span class="fw-bold"><%= @movie.duration%></span> min</p>
    <p>Released?: <span class="fw-bold"><%=@movie.is_released ? "Yes" : "No"%></span></p>
    <p>Summary: <span><%= @movie.summary%></span></p>
  </div>

  <div class="mt-2 mb-4">
    <%= link_to "Edit", edit_movie_path, class: "btn btn-dark"%>
  </div>
</div>